baseURL = "https://jinntec.github.io/fore-docs/"
languageCode = "en-us"
title = "Fore Documentation"
theme = "learn"
canonifyURLs = true

[params]
    themeVariant = "tuttle"
    siteLandingPage = "https://jinntec.github.io/fore-docs"
    landingPageName = "<i class='fas fa-home'></i> Tuttle Documentation"
    editURL = "https://github.com/jinntec/fore-docs/edit/main/content/"

[[menu.shortcuts]]
    name = "<i class='fas fa-tags'></i> Tags"
    url = "/tags"
    weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON"]