baseURL = "https://jinntec.github.io/fore-docs/"
languageCode = "en-us"
title = "Fore Documentation"
theme = "learn"
canonifyURLs = true

[params]
    editURL = "https://github.com/Jinntec/fore-docs/tree/main/content/"
    themeVariant = "fore"
    siteLandingPage = "https://jinntec.github.io/fore-docs"
    landingPageName = "Fore Documentation"
    disableLandingPageButton = true
    demoUrl = "https://jinntec.github.io/Fore/demo/"
    disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
    name = "<i class='fas fa-tags'></i> Tags"
    url = "/fore-docs/tags"
    weight = 30

[[menu.shortcuts]]
    name = "<i class='fab fa-github'></i> Github"
    identifier = "github"
    url = "https://github.com/jinntec/Fore"
    weight = 10

[[menu.shortcuts]]
    name = "<i class='fa fa-link'></i> Links"
    identifier = "links"
    url = "links"
    weight = 11


[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

